[package]
name = 'Woolf'
version = '1.0.0'

[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'main'
subdir = 'aptos-move/framework/aptos-framework'

[dependencies.AptosToken]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'main'
subdir = 'aptos-move/framework/aptos-token'

[addresses]
woolf_deployer="_"
woolf_risky_gamer="0x648f926c3739dcde18d586bd81b93e9a3e7b3d3b57501991c9e91144d6c1ebbd"
woolf_deployer_fund="0xf2db9526accac625e00dac4c3d3aa27bf55ec7d24b0723c1d1a35b42757b3a1e"
# WoolfResourceDeployer="0x45c8afc3a42f5310146f4cb50da818748f3a4ef2e69c86d3a3ee233869e02286"