[package]
name = 'woolf'
version = '1.0.0'

[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = '01108a2345b87d539d54a67b32db55193f9ace40'
subdir = 'aptos-move/framework/aptos-framework'

[dependencies.AptosToken]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = '01108a2345b87d539d54a67b32db55193f9ace40'
subdir = 'aptos-move/framework/aptos-token'

#[dependencies.WoolfResourceAccount]
#local = "../WoolfResourceAccount"

[addresses]
woolf_deployer="_"
woolf_deployer_fund="0xf2db9526accac625e00dac4c3d3aa27bf55ec7d24b0723c1d1a35b42757b3a1e"
# WoolfResourceDeployer="0x45c8afc3a42f5310146f4cb50da818748f3a4ef2e69c86d3a3ee233869e02286"